# Generated by Django 5.1.1 on 2025-05-11 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_player_delete_gameuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
        migrations.RemoveField(
            model_name='player',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_active',
        ),
        migrations.AddField(
            model_name='player',
            name='businessCategory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='businessGoal',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='businessLocation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='businessName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='businessType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='capital',
            field=models.IntegerField(default=50000),
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='balance',
            field=models.IntegerField(default=50000),
        ),
    ]
