# Generated by Django 5.1.1 on 2025-05-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_remove_player_created_at_remove_player_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='targetMarket',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
