# Generated by Django 5.1.1 on 2025-05-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_player_targetmarket'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='numberOfWorkers',
            field=models.IntegerField(default=0),
        ),
    ]
