# Generated by Django 5.1.1 on 2025-05-21 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0005_player_numberofworkers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='numberOfWorkers',
            new_name='maxNumberOfWorkers',
        ),
    ]
